name: Node Continuous Integration

on:
  [push, pull_request]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Upload coverage to Codecov (script)
        uses: codecov/codecov-action@v1
        with:
          node-version: 12
          files: ./coverage/clover.xml
          run: bash  <(curl -s https://codecov.io/bash) -f clover.xml
      